gcp --parents ./CMakeLists.txt ../build_essentials/
gcp --parents ./Makefile ../build_essentials/
gcp --parents ./bsp/board/bl702/bl702_config.h ../build_essentials/
gcp --parents ./bsp/board/bl702/bl702_xt/clock_config.h ../build_essentials/
gcp --parents ./bsp/board/bl702/bl702_xt/peripheral_config.h ../build_essentials/
gcp --parents ./bsp/board/bl702/bl702_xt/pinmux_config.h ../build_essentials/
gcp --parents ./bsp/board/bl702/board.c ../build_essentials/
gcp --parents ./bsp/bsp_common/platform/bflb_platform.c ../build_essentials/
gcp --parents ./bsp/bsp_common/platform/bflb_platform.h ../build_essentials/
gcp --parents ./bsp/bsp_common/platform/syscalls.c ../build_essentials/
gcp --parents ./build_script.sh ../build_essentials/
gcp --parents ./ccc.sh ../build_essentials/
gcp --parents ./common/CMakeLists.txt ../build_essentials/
gcp --parents ./common/bl_math/arm_dsp_wrapper.c ../build_essentials/
gcp --parents ./common/bl_math/arm_dsp_wrapper.h ../build_essentials/
gcp --parents ./common/device/drv_device.c ../build_essentials/
gcp --parents ./common/device/drv_device.h ../build_essentials/
gcp --parents ./common/list/drv_list.h ../build_essentials/
gcp --parents ./common/memheap/drv_mmheap.c ../build_essentials/
gcp --parents ./common/memheap/drv_mmheap.h ../build_essentials/
gcp --parents ./common/misc/compiler/common.h ../build_essentials/
gcp --parents ./common/misc/compiler/gcc.h ../build_essentials/
gcp --parents ./common/misc/misc.c ../build_essentials/
gcp --parents ./common/misc/misc.h ../build_essentials/
gcp --parents ./common/partition/partition.c ../build_essentials/
gcp --parents ./common/partition/partition.h ../build_essentials/
gcp --parents ./common/pid/pid.c ../build_essentials/
gcp --parents ./common/pid/pid.h ../build_essentials/
gcp --parents ./common/ring_buffer/ring_buffer.c ../build_essentials/
gcp --parents ./common/ring_buffer/ring_buffer.h ../build_essentials/
gcp --parents ./common/soft_crc/softcrc.c ../build_essentials/
gcp --parents ./common/soft_crc/softcrc.h ../build_essentials/
gcp --parents ./common/timestamp/timestamp.c ../build_essentials/
gcp --parents ./common/timestamp/timestamp.h ../build_essentials/
gcp --parents ./components/ble/CMakeLists.txt ../build_essentials/
gcp --parents ./components/ble/bl702_rf/lib/libbl702_rf.a ../build_essentials/
gcp --parents ./components/ble/ble_flags.cmake ../build_essentials/
gcp --parents ./components/ble/ble_stack/bl_hci_wrapper/bl_hci_wrapper.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/bl_hci_wrapper/bl_hci_wrapper.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/cli_cmds/empty ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/atomic_c.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/buf.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/dec.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/dummy.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/atomic.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/errno.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/__assert.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/byteorder.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/dlist.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/printk.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/slist.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/stack.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/util.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/misc/utils_string.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/net/buf.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/toolchain/common.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/toolchain/gcc.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/toolchain.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/work_q.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/include/zephyr/types.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/log.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/log.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/poll.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/rpa.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/rpa.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/aes.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/cbc_mode.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ccm_mode.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/cmac_mode.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/constants.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ctr_mode.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ctr_prng.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ecc.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ecc_dh.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ecc_dsa.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/ecc_platform_specific.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/hmac.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/hmac_prng.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/sha256.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/include/tinycrypt/utils.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/aes_decrypt.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/aes_encrypt.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/cbc_mode.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ccm_mode.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/cmac_mode.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ctr_mode.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ctr_prng.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ecc.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ecc_dh.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ecc_dsa.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/ecc_platform_specific.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/hmac.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/hmac_prng.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/sha256.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/tinycrypt/source/utils.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/utils.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/common/work_q.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/hci_onchip/hci_driver.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/hci_onchip/hci_internal.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/att.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/att_internal.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/conn.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/conn_internal.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/crypto.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/crypto.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/ecc.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/gatt.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/gatt_internal.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/hci_core.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/hci_core.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/hci_ecc.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/hci_ecc.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/keys.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/keys.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/l2cap.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/l2cap_internal.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/monitor.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/settings.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/settings.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/smp.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/smp.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/host/uuid.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/addr.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/att.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/bluetooth.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/buf.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/conn.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/crypto.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/gap.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/gatt.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/hci_err.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/hci_host.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/hci_vs.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/l2cap.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/bluetooth/uuid.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/include/drivers/bluetooth/hci_driver.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/port/bl_port.c ../build_essentials/
gcp --parents ./components/ble/ble_stack/port/include/bl_port.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/port/include/config.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/port/include/zephyr.h ../build_essentials/
gcp --parents ./components/ble/ble_stack/services/empty ../build_essentials/
gcp --parents ./components/ble/blecontroller/ble_inc/ble_lib_api.h ../build_essentials/
gcp --parents ./components/ble/blecontroller/ble_inc/hci_onchip.h ../build_essentials/
gcp --parents ./components/ble/blecontroller/lib/libblecontroller.a ../build_essentials/
gcp --parents ./components/freertos/CMakeLists.txt ../build_essentials/
gcp --parents ./components/freertos/croutine.c ../build_essentials/
gcp --parents ./components/freertos/event_groups.c ../build_essentials/
gcp --parents ./components/freertos/include/FreeRTOS.h ../build_essentials/
gcp --parents ./components/freertos/include/croutine.h ../build_essentials/
gcp --parents ./components/freertos/include/deprecated_definitions.h ../build_essentials/
gcp --parents ./components/freertos/include/event_groups.h ../build_essentials/
gcp --parents ./components/freertos/include/list.h ../build_essentials/
gcp --parents ./components/freertos/include/mpu_wrappers.h ../build_essentials/
gcp --parents ./components/freertos/include/portable.h ../build_essentials/
gcp --parents ./components/freertos/include/projdefs.h ../build_essentials/
gcp --parents ./components/freertos/include/queue.h ../build_essentials/
gcp --parents ./components/freertos/include/semphr.h ../build_essentials/
gcp --parents ./components/freertos/include/stack_macros.h ../build_essentials/
gcp --parents ./components/freertos/include/stream_buffer.h ../build_essentials/
gcp --parents ./components/freertos/include/task.h ../build_essentials/
gcp --parents ./components/freertos/include/timers.h ../build_essentials/
gcp --parents ./components/freertos/list.c ../build_essentials/
gcp --parents ./components/freertos/portable/MemMang/heap_5.c ../build_essentials/
gcp --parents ./components/freertos/portable/gcc/risc-v/bl702/FreeRTOSConfig.h ../build_essentials/
gcp --parents ./components/freertos/portable/gcc/risc-v/bl702/freertos_risc_v_chip_specific_extensions.h ../build_essentials/
gcp --parents ./components/freertos/portable/gcc/risc-v/bl702/port.c ../build_essentials/
gcp --parents ./components/freertos/portable/gcc/risc-v/bl702/portASM.S ../build_essentials/
gcp --parents ./components/freertos/portable/gcc/risc-v/bl702/portmacro.h ../build_essentials/
gcp --parents ./components/freertos/queue.c ../build_essentials/
gcp --parents ./components/freertos/stream_buffer.c ../build_essentials/
gcp --parents ./components/freertos/tasks.c ../build_essentials/
gcp --parents ./components/freertos/timers.c ../build_essentials/
gcp --parents ./components/mbedtls/CMakeLists.txt ../build_essentials/
gcp --parents ./components/mbedtls/bflb_port/inc/mbedtls_bflb_config.h ../build_essentials/
gcp --parents ./components/mbedtls/bflb_port/inc/mbedtls_port_config.h ../build_essentials/
gcp --parents ./components/mbedtls/bflb_port/src/bflb_aes.c ../build_essentials/
gcp --parents ./components/mbedtls/bflb_port/src/bflb_ccm.c ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/aes.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/ccm.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/cipher.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/error.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/platform.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/platform_util.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/sha256.h ../build_essentials/
gcp --parents ./components/mbedtls/include/mbedtls/threading.h ../build_essentials/
gcp --parents ./components/mbedtls/include/psa/empty ../build_essentials/
gcp --parents ./components/mbedtls/library/common.h ../build_essentials/
gcp --parents ./components/mbedtls/library/platform_util.c ../build_essentials/
gcp --parents ./components/mbedtls/library/sha256.c ../build_essentials/
gcp --parents ./components/xz/CMakeLists.txt ../build_essentials/
gcp --parents ./components/xz/xz.h ../build_essentials/
gcp --parents ./components/xz/xz_config.h ../build_essentials/
gcp --parents ./components/xz/xz_crc32.c ../build_essentials/
gcp --parents ./components/xz/xz_dec_lzma2.c ../build_essentials/
gcp --parents ./components/xz/xz_dec_stream.c ../build_essentials/
gcp --parents ./components/xz/xz_decompress.c ../build_essentials/
gcp --parents ./components/xz/xz_lzma2.h ../build_essentials/
gcp --parents ./components/xz/xz_port.c ../build_essentials/
gcp --parents ./components/xz/xz_private.h ../build_essentials/
gcp --parents ./components/xz/xz_stream.h ../build_essentials/
gcp --parents ./copy_essentials_for_building.sh ../build_essentials/
gcp --parents ./drivers/bl702_driver/CMakeLists.txt ../build_essentials/
gcp --parents ./drivers/bl702_driver/blsp_boot2_iap_flash.ld ../build_essentials/
gcp --parents ./drivers/bl702_driver/cpu_flags.cmake ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/default_config/adc_config.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/default_config/i2s_config.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/default_config/uart_config.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_acomp.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_adc.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_boot2.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_cam.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_clock.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_common.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_dac.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_dma.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_emac.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_flash.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_gpio.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_i2c.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_i2s.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_keyscan.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_mjpeg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_mtimer.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_pm.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_pm_util.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_pwm.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_qdec.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_rtc.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_sec_aes.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_sec_dsa.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_sec_ecdsa.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_sec_hash.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_spi.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_timer.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_uart.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_usb.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/inc/hal_wdt.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_acomp.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_adc.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_boot2.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_cam.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_clock.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_common.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_dac.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_dma.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_emac.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_flash.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_gpio.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_i2c.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_i2s.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_keyscan.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_mjpeg.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_mtimer.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_pm.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_pm_util.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_pwm.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_qdec.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_rtc.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_sec_aes.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_sec_dsa.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_sec_ecdsa.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_sec_hash.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_spi.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_timer.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_uart.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_usb.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/hal_drv/src/hal_wdt.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/aon_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/bl702.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/cam_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/dma_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/ef_ctrl_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/ef_data_0_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/emac_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/glb_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/gpip_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/hbn_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/i2c_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/i2s_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/ir_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/kys_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/l1c_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/mjpeg_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/pds_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/pwm_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/qdec_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/sec_dbg_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/sec_eng_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/sf_ctrl_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/spi_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/timer_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/tzc_sec_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/uart_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/regs/usb_reg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/risc-v/Core/Include/clic.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/risc-v/Core/Include/riscv_encoding.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/startup/GCC/entry.S ../build_essentials/
gcp --parents ./drivers/bl702_driver/startup/GCC/start_load.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/startup/interrupt.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/startup/system_bl702.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/startup/system_bl702.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_acomp.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_adc.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_aon.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_cam.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_common.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_dac.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_dma.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_ef_ctrl.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_emac.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_glb.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_gpio.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_hbn.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_i2c.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_i2s.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_ir.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_kys.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_l1c.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_mjpeg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_pds.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_psram.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_pwm.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_qdec.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_romdriver.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sec_dbg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sec_eng.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sf_cfg.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sf_cfg_ext.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sf_ctrl.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sflash.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_sflash_ext.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_spi.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_timer.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_uart.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_usb.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_xip_sflash.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/inc/bl702_xip_sflash_ext.h ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_acomp.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_adc.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_aon.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_cam.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_common.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_dac.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_dma.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_ef_ctrl.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_emac.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_glb.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_hbn.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_i2c.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_i2c_gpio_sim.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_i2s.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_ir.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_kys.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_l1c.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_mjpeg.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_pds.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_psram.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_pwm.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_qdec.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_romapi.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sec_dbg.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sec_eng.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sf_cfg.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sf_cfg_ext.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sf_ctrl.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sflash.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_sflash_ext.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_spi.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_timer.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_uart.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_usb.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_xip_sflash.c ../build_essentials/
gcp --parents ./drivers/bl702_driver/std_drv/src/bl702_xip_sflash_ext.c ../build_essentials/
gcp --parents ./examples/boot2_custom/CMakeLists.txt ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader.h ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_ble.c ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_ble.h ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_cmds.c ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_cmds.h ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_interface.c ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_interface.h ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_uart.c ../build_essentials/
gcp --parents ./examples/boot2_custom/bflb_eflash_loader_uart.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_boot_decompress.c ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_boot_decompress.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_boot_parser.c ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_boot_parser.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_bootinfo.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_common.c ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_common.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_media_boot.c ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_media_boot.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_port.c ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_port.h ../build_essentials/
gcp --parents ./examples/boot2_custom/blsp_version.h ../build_essentials/
gcp --parents ./examples/boot2_custom/main.c ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-ar ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-g++ ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-gcc ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-objcopy ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-objdump ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-ranlib ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/bin/riscv64-unknown-elf-size ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/include/stdarg.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/include/stdbool.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/include/stddef.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/include/stdint.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/rv32imafc/ilp32f/libgcc.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/rv64imafdc/lp64d/crtbegin.o ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/rv64imafdc/lp64d/crtend.o ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/lib/gcc/riscv64-unknown-elf/10.2.0/rv64imafdc/lp64d/libgcc.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/libexec/gcc/riscv64-unknown-elf/10.2.0/cc1 ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/libexec/gcc/riscv64-unknown-elf/10.2.0/cc1plus ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/libexec/gcc/riscv64-unknown-elf/10.2.0/collect2 ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/libexec/gcc/riscv64-unknown-elf/10.2.0/liblto_plugin.so ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/bin/as ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/bin/ld ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/_ansi.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/_newlib_version.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/assert.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/_default_types.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/_types.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/fastmath.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/ieeefp.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/stdlib.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/machine/types.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/math.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/newlib.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/reent.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/stdint.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/stdio.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/stdlib.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/string.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/_intsup.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/_pthreadtypes.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/_stdint.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/_timespec.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/_types.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/cdefs.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/config.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/features.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/lock.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/reent.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/sched.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/stdio.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/string.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/types.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/sys/unistd.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/include/unistd.h ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/nano.specs ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv32imafc/ilp32f/libc.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv32imafc/ilp32f/libc_nano.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv32imafc/ilp32f/libg_nano.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv32imafc/ilp32f/libgloss_nano.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv32imafc/ilp32f/libm_nano.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv64imafdc/lp64d/crt0.o ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv64imafdc/lp64d/libc.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv64imafdc/lp64d/libgloss.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv64imafdc/lp64d/libm.a ../build_essentials/
gcp --parents ./toolchain_essentials/riscv/Darwin/riscv64-unknown-elf/lib/rv64imafdc/lp64d/libstdc++.a ../build_essentials/
gcp --parents ./tools/bflb_flash_tool/img/project.bin ../build_essentials/
gcp --parents ./tools/cmake/compiler_flags.cmake ../build_essentials/
gcp --parents ./tools/cmake/riscv64-unknown-elf-gcc.cmake ../build_essentials/
gcp --parents ./tools/cmake/tools.cmake ../build_essentials/
